name: webview_ios
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://example.com
publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: WebviewIosPlugin